#############################################################################
# Makefile for building: Convert
# Generated by qmake (2.01a) (Qt 4.5.3) on: ?? 3? 19 09:13:23 2010
# Project:  Convert.pro
# Template: app
# Command: /home/student/qtsdk-2009.04/qt/bin/qmake -unix -o Makefile Convert.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../qtsdk-2009.04/qt/mkspecs/linux-g++-64 -I. -I../../qtsdk-2009.04/qt/include/QtCore -I../../qtsdk-2009.04/qt/include/QtGui -I../../qtsdk-2009.04/qt/include -I. -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-rpath,/home/student/qtsdk-2009.04/qt/lib
LIBS          = $(SUBLIBS)  -L/home/student/qtsdk-2009.04/qt/lib -lQtGui -L/home/student/qtsdk-2009.04/qt/lib -L/usr/X11R6/lib64 -pthread -lfreetype -lgobject-2.0 -lSM -lICE -pthread -pthread -lXrender -lfontconfig -lXext -lX11 -lQtCore -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/student/qtsdk-2009.04/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = qjd_convert_help.cpp \
		main.cpp \
		qjd_convert_mainwindow.cpp \
		qjddatastream.cpp \
		qjdsegybh.cpp \
		qjdsegyth.cpp \
		qjdtraceheader.cpp moc_qjd_convert_help.cpp \
		moc_qjd_convert_mainwindow.cpp \
		qrc_image.cpp
OBJECTS       = qjd_convert_help.o \
		main.o \
		qjd_convert_mainwindow.o \
		qjddatastream.o \
		qjdsegybh.o \
		qjdsegyth.o \
		qjdtraceheader.o \
		moc_qjd_convert_help.o \
		moc_qjd_convert_mainwindow.o \
		qrc_image.o
DIST          = ../../qtsdk-2009.04/qt/mkspecs/common/g++.conf \
		../../qtsdk-2009.04/qt/mkspecs/common/unix.conf \
		../../qtsdk-2009.04/qt/mkspecs/common/linux.conf \
		../../qtsdk-2009.04/qt/mkspecs/qconfig.pri \
		../../qtsdk-2009.04/qt/mkspecs/features/qt_functions.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/qt_config.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/exclusive_builds.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/default_pre.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/debug.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/default_post.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/warn_on.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/qt.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/unix/thread.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/moc.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/resources.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/uic.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/yacc.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/lex.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/include_source_dir.prf \
		Convert.pro
QMAKE_TARGET  = Convert
DESTDIR       = 
TARGET        = Convert

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_qjd_convert_help.h ui_qjd_convert_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Convert.pro  ../../qtsdk-2009.04/qt/mkspecs/linux-g++-64/qmake.conf ../../qtsdk-2009.04/qt/mkspecs/common/g++.conf \
		../../qtsdk-2009.04/qt/mkspecs/common/unix.conf \
		../../qtsdk-2009.04/qt/mkspecs/common/linux.conf \
		../../qtsdk-2009.04/qt/mkspecs/qconfig.pri \
		../../qtsdk-2009.04/qt/mkspecs/features/qt_functions.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/qt_config.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/exclusive_builds.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/default_pre.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/debug.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/default_post.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/warn_on.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/qt.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/unix/thread.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/moc.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/resources.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/uic.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/yacc.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/lex.prf \
		../../qtsdk-2009.04/qt/mkspecs/features/include_source_dir.prf \
		/home/student/qtsdk-2009.04/qt/lib/libQtGui.prl \
		/home/student/qtsdk-2009.04/qt/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile Convert.pro
../../qtsdk-2009.04/qt/mkspecs/common/g++.conf:
../../qtsdk-2009.04/qt/mkspecs/common/unix.conf:
../../qtsdk-2009.04/qt/mkspecs/common/linux.conf:
../../qtsdk-2009.04/qt/mkspecs/qconfig.pri:
../../qtsdk-2009.04/qt/mkspecs/features/qt_functions.prf:
../../qtsdk-2009.04/qt/mkspecs/features/qt_config.prf:
../../qtsdk-2009.04/qt/mkspecs/features/exclusive_builds.prf:
../../qtsdk-2009.04/qt/mkspecs/features/default_pre.prf:
../../qtsdk-2009.04/qt/mkspecs/features/debug.prf:
../../qtsdk-2009.04/qt/mkspecs/features/default_post.prf:
../../qtsdk-2009.04/qt/mkspecs/features/warn_on.prf:
../../qtsdk-2009.04/qt/mkspecs/features/qt.prf:
../../qtsdk-2009.04/qt/mkspecs/features/unix/thread.prf:
../../qtsdk-2009.04/qt/mkspecs/features/moc.prf:
../../qtsdk-2009.04/qt/mkspecs/features/resources.prf:
../../qtsdk-2009.04/qt/mkspecs/features/uic.prf:
../../qtsdk-2009.04/qt/mkspecs/features/yacc.prf:
../../qtsdk-2009.04/qt/mkspecs/features/lex.prf:
../../qtsdk-2009.04/qt/mkspecs/features/include_source_dir.prf:
/home/student/qtsdk-2009.04/qt/lib/libQtGui.prl:
/home/student/qtsdk-2009.04/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile Convert.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Convert1.0.0 || $(MKDIR) .tmp/Convert1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Convert1.0.0/ && $(COPY_FILE) --parents qjd_convert_help.h qjd_convert_mainwindow.h qjddatastream.h qjdsegybh.h qjdsegyth.h qjdtraceheader.h .tmp/Convert1.0.0/ && $(COPY_FILE) --parents image.qrc .tmp/Convert1.0.0/ && $(COPY_FILE) --parents qjd_convert_help.cpp main.cpp qjd_convert_mainwindow.cpp qjddatastream.cpp qjdsegybh.cpp qjdsegyth.cpp qjdtraceheader.cpp .tmp/Convert1.0.0/ && $(COPY_FILE) --parents qjd_convert_help.ui qjd_convert_mainwindow.ui .tmp/Convert1.0.0/ && $(COPY_FILE) --parents convert_en.ts convert_zh.ts .tmp/Convert1.0.0/ && (cd `dirname .tmp/Convert1.0.0` && $(TAR) Convert1.0.0.tar Convert1.0.0 && $(COMPRESS) Convert1.0.0.tar) && $(MOVE) `dirname .tmp/Convert1.0.0`/Convert1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Convert1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qjd_convert_help.cpp moc_qjd_convert_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qjd_convert_help.cpp moc_qjd_convert_mainwindow.cpp
moc_qjd_convert_help.cpp: ui_qjd_convert_help.h \
		qjd_convert_help.h
	/home/student/qtsdk-2009.04/qt/bin/moc $(DEFINES) $(INCPATH) qjd_convert_help.h -o moc_qjd_convert_help.cpp

moc_qjd_convert_mainwindow.cpp: qjdtraceheader.h \
		qjddatastream.h \
		qjdsegybh.h \
		qjdsegyth.h \
		qjd_convert_help.h \
		ui_qjd_convert_help.h \
		qjd_convert_mainwindow.h
	/home/student/qtsdk-2009.04/qt/bin/moc $(DEFINES) $(INCPATH) qjd_convert_mainwindow.h -o moc_qjd_convert_mainwindow.cpp

compiler_rcc_make_all: qrc_image.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_image.cpp
qrc_image.cpp: image.qrc \
		image/Crystal_Clear_action_edit_add.png \
		image/Crystal_Clear_action_edit_remove.png \
		image/dialog-ok.png \
		image/Torchlight_help.png \
		image/edit-delete.png \
		image/document-open.png \
		image/go-next.png \
		image/document-save.png
	/home/student/qtsdk-2009.04/qt/bin/rcc -name image image.qrc -o qrc_image.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_qjd_convert_help.h ui_qjd_convert_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_qjd_convert_help.h ui_qjd_convert_mainwindow.h
ui_qjd_convert_help.h: qjd_convert_help.ui
	/home/student/qtsdk-2009.04/qt/bin/uic qjd_convert_help.ui -o ui_qjd_convert_help.h

ui_qjd_convert_mainwindow.h: qjd_convert_mainwindow.ui
	/home/student/qtsdk-2009.04/qt/bin/uic qjd_convert_mainwindow.ui -o ui_qjd_convert_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

qjd_convert_help.o: qjd_convert_help.cpp qjd_convert_help.h \
		ui_qjd_convert_help.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qjd_convert_help.o qjd_convert_help.cpp

main.o: main.cpp qjd_convert_mainwindow.h \
		qjdtraceheader.h \
		qjddatastream.h \
		qjdsegybh.h \
		qjdsegyth.h \
		qjd_convert_help.h \
		ui_qjd_convert_help.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qjd_convert_mainwindow.o: qjd_convert_mainwindow.cpp qjd_convert_mainwindow.h \
		qjdtraceheader.h \
		qjddatastream.h \
		qjdsegybh.h \
		qjdsegyth.h \
		qjd_convert_help.h \
		ui_qjd_convert_help.h \
		ui_qjd_convert_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qjd_convert_mainwindow.o qjd_convert_mainwindow.cpp

qjddatastream.o: qjddatastream.cpp qjddatastream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qjddatastream.o qjddatastream.cpp

qjdsegybh.o: qjdsegybh.cpp qjdsegybh.h \
		qjddatastream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qjdsegybh.o qjdsegybh.cpp

qjdsegyth.o: qjdsegyth.cpp qjdsegyth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qjdsegyth.o qjdsegyth.cpp

qjdtraceheader.o: qjdtraceheader.cpp qjdtraceheader.h \
		qjddatastream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qjdtraceheader.o qjdtraceheader.cpp

moc_qjd_convert_help.o: moc_qjd_convert_help.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qjd_convert_help.o moc_qjd_convert_help.cpp

moc_qjd_convert_mainwindow.o: moc_qjd_convert_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qjd_convert_mainwindow.o moc_qjd_convert_mainwindow.cpp

qrc_image.o: qrc_image.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_image.o qrc_image.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

